package com.denovo.enums;

public enum ConfigProperties {

    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RUNMODE,
    BROWSER,

    SENDRESULTTOELK,
}
