
image: maven:3.6.3-jdk-11
pipelines:
  branches:
    master:
     - step:
         name: Manual step
         script:
          - echo "This step runs once you click the 'Run' button"

     - step:
         name: Build and Test
         caches:
          - maven
         services:
           - docker
         script:
          - docker-compose -f selenoid-docker-compose.yaml up
          - mvn clean test -Pweb

definitions:
 services:
   docker:
     memory: 3072
  #selenium-chrome:
   #image: selenium/standalone-chrome:latest
   #ports:
    #- "4444:4444"



