options:
  size: 2x
  ubuntu: true

image: maven:3.6.3-jdk-11
pipelines:
  branches:
    master:
    - step:
        name: Manual step
        script:
          - echo "This step runs once you click the 'Run' button"

    - step:
        name: Build and Test
        caches:
          - maven
        services:
          -
        script:
          - mvn clean test -Pweb

