options:
  max-time: 30
  size: 2x

image: maven:3.6.3-jdk-11
pipelines:
  branches:
    master:
     - step:
         name: Build and Test
         caches:
          - maven
         services:
           - selenium-chrome
         script:
          - mvn clean test -Pweb
         after-script:
          - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; else echo "Step failed"; fi;
          - mvn clean test -Psendemail


definitions:
 services:
  selenium-chrome:
   image: selenium/standalone-chrome:latest
