image: maven:3.6.3-jdk-11
pipelines:
  branches:
    master:
     - step:
         name: Build and Test
         caches:
          - maven
         services:
           - selenium-chrome
         script:
          - mvn clean test -Pweb


definitions:
 services:
  selenium-chrome:
   image: selenium/standalone-chrome:latest


