
image: maven:3.6.3-jdk-11
pipelines:
  branches:
    master:
     - step:
         name: Manual step
         script:
          - echo "This step runs once you click the 'Run' button"

     - step:
         name: Build and Test
         caches:
          - maven
         script:
          - docker-compose -f selenoid-docker-compose.yaml
          - mvn clean test -Pweb

definitions:
 services:
  selenium-chrome:
   image: selenium/standalone-chrome:latest
   ports:
    - "4444:4444"



