version: '3'
networks:
  selenoid:
      external:
        name: slenoid


services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "/C/Users/MY PC/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/C/Users/MY PC/selenoid/video:/opt/selenoid/video/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Users/MY PC/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video",
              "-container-network", "selenoid","-limit","30","-mem","2g","-cpu","1"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - selenoid
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  jenkins:
    networks:
      - selenoid
    image: "jenkins/jenkins:lts-jdk11"
    volumes:
      - E:\jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - selenoid
    ports:
      - "8081:8080"
      - "50000:50000"
    restart: "always"


