version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/C/Users/MY PC/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/C/Users/MY PC/selenoid/video:/opt/selenoid/video/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Users/MY PC/selenoid/video
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  jenkins:
    image: "jenkins/jenkins:lts-jdk11"
    volumes:
      - E:\jenkins_home:/var/jenkins_home
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8081:8080"
      - "50000:50000"




