name: run web test in github actions

on: workflow_dispatch

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: false

    steps:
      - name: pull the project  into the runner
        uses: actions/checkout@v3

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'


      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: run the web test
        run:
          mvn clean test

  jobs2:
      runs-on: ubuntu-latest
      if: ${{ failure() }}
      needs: run-web-test
      steps:
        - name: Set up Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'

        - name: send Email
          run:
            import javax.mail.*;
        
        
            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            
            
            Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() 
             {
                return new PasswordAuthentication("bmurthy@denovosystem.com", "${{ secrets.USER_PASSWORD }}");
              }
            });
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("bmurthy@denovosystem.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse("bhaskarmurthy215@gmail.com"));
            message.setSubject("Build failed");
            message.setText("The build failed. Please check the logs.");
            
            Transport.send(message);
