name: run web test in github actions

on: workflow_dispatch

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: false

    steps:
      - name: pull the project  into the runner
        uses: actions/checkout@v3

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'


      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: run the web test
        run:
          mvn clean test

  jobs2:
      runs-on: ubuntu-latest
      if: ${{ failure() }}
      needs: run-web-test
      steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          run: pip install smtplib

        - name: send Email
          run:
            import smtplib
            from email.mime.text import MIMEText

        
            smtp_server = 'smtp.gmail.com'
            smtp_port = 587
            smtp_username = ${{ secrets.USER_EMAIL }}
            smtp_password = ${{ secrets.USER_PASSWORD }}
            smtp_connection = smtplib.SMTP(smtp_server, smtp_port)
            smtp_connection.starttls()
            smtp_connection.login(smtp_username, smtp_password)
          
        
            message = MIMEText('The build failed. Please check the logs.')
            message['Subject'] = 'Build failed'
            message['From'] = 'bmurthy@denovosystem.com'
            message['To'] = 'bhaskarmurthy215@gmail.com'
            smtp_connection.sendmail('bmurthy@denovosystem.com', 'bhaskarmurthy215@gmail.com', message.as_string())
            smtp_connection.quit()
